source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.6'
gem 'json', '~> 1.8.3'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'omniauth-google-oauth2', '~> 0.2.10'
# gem 'passenger','4.0.49' 
# or gem 'passenger','4.0.59'
# run if not already done previously 'passenger-install-apache2-module'